const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let current={result:null,transcript:""}, mediaRecorder=null, chunks=[], recordStart=0, recordTimer=null, audioStream=null;
function showError(msg){$("#error").textContent=msg||""} function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2600)}
async function api(url,options={}){const r=await fetch(url,options);let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.detail||"Something went wrong.");return d}
$$('.nav').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));
$$('.source-tab').forEach(b=>b.onclick=()=>{$$('.source-tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#tab-'+b.dataset.tab).classList.add('active')});
$('#sampleBtn').onclick=async()=>{try{const r=await fetch('/sample_transcript.txt');$('#transcript').value=await r.text();toast('Sample loaded')}catch{showError('Sample transcript could not be loaded.')}};
$('#fileInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;$('#fileName').textContent=f.name;try{const fd=new FormData();fd.append('file',f);$('#transcript').value=(await api('/api/read-file',{method:'POST',body:fd})).text;toast('Transcript imported')}catch(err){showError(err.message)}};
$('#mediaInput').onchange=e=>{const f=e.target.files[0];if(f)$('#mediaName').textContent=`${f.name} · ${(f.size/1048576).toFixed(1)} MB`};
$('#transcribeBtn').onclick=()=>transcribeFile($('#mediaInput').files[0]);
async function transcribeFile(f){if(!f)return showError('Choose an audio or video file first.');showError('');$('#transcribeProgress').style.display='block';$('#transcribeBtn').disabled=true;try{const fd=new FormData();fd.append('file',f);fd.append('model_size',$('#model').value);fd.append('language',$('#language').value);const d=await api('/api/transcribe',{method:'POST',body:fd});$('#transcript').value=d.text;$$('.source-tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));document.querySelector('[data-tab="paste"]').classList.add('active');$('#tab-paste').classList.add('active');toast('Transcription complete')}catch(err){showError(err.message)}finally{$('#transcribeBtn').disabled=false;$('#transcribeProgress').style.display='none'}}
function timerText(ms){const s=Math.floor(ms/1000),m=Math.floor(s/60),sec=s%60;return `${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`}
$('#startRecord').onclick=async()=>{showError('');if(!navigator.mediaDevices?.getUserMedia)return showError('Your browser does not support microphone recording.');try{audioStream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];mediaRecorder=new MediaRecorder(audioStream);mediaRecorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};mediaRecorder.onstop=async()=>{audioStream?.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:mediaRecorder.mimeType||'audio/webm'});const f=new File([blob],`notex-live-${Date.now()}.webm`,{type:blob.type});$('#recordState').textContent='Transcribing meeting…';$('#startRecord').disabled=true;try{await transcribeFile(f)}finally{$('#startRecord').disabled=false;$('#recordState').textContent='Ready to record'}};mediaRecorder.start(250);recordStart=Date.now();$('#startRecord').disabled=true;$('#stopRecord').disabled=false;$('#recordRing').classList.add('recording');$('#recordState').textContent='Recording live meeting';recordTimer=setInterval(()=>$('#recordTimer').textContent=timerText(Date.now()-recordStart),250);toast('Live recording started')}catch(err){showError('Microphone permission was denied or unavailable.')}};
$('#stopRecord').onclick=()=>{if(mediaRecorder?.state==='recording'){mediaRecorder.stop();clearInterval(recordTimer);$('#stopRecord').disabled=true;$('#recordRing').classList.remove('recording');$('#recordTimer').textContent=timerText(Date.now()-recordStart);toast('Recording stopped')}};
$('#analyzeBtn').onclick=async()=>{const transcript=$('#transcript').value.trim();if(!transcript)return showError('Add a transcript before generating notes.');showError('');const b=$('#analyzeBtn');b.disabled=true;b.querySelector('span').textContent='Analyzing…';try{const d=await api('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transcript,title:$('#title').value,summary_sentences:+$('#summaryLen').value,keywords:+$('#keywordLen').value})});current={result:d.result,transcript:d.transcript};render(d.result,d.transcript);$('#results').scrollIntoView({behavior:'smooth'});toast('Notes generated')}catch(err){showError(err.message)}finally{b.disabled=false;b.querySelector('span').textContent='Generate notes'}};
function render(r,transcript){$('#emptyState').hidden=true;$('#resultsContent').hidden=false;const st=r.stats||{},tone=r.overall_sentiment?.label||'Neutral';$('#metrics').innerHTML=[['WORDS',st.word_count??'—'],['EST. DURATION',`${st.est_duration_min??'—'} min`],['READING TIME',`${st.est_reading_min??'—'} min`],['OVERALL TONE',tone]].map((x,i)=>`<div class="metric ${i===3?'tone':''}"><small>${x[0]}</small><strong>${esc(x[1])}</strong></div>`).join('');fillList('#summary',r.summary,'No summary generated.');fillList('#decisions',r.decisions,'No decisions detected.');$('#actions').innerHTML=(r.action_items_tagged||[]).map(a=>`<li>${esc(a.text)} <span class="priority ${String(a.priority||'normal').toLowerCase()}">${esc(a.priority||'Normal')}</span></li>`).join('')||'<li>No action items detected.</li>';$('#keywords').innerHTML=(r.keywords||[]).map(k=>`<span class="chip">${esc(k)}</span>`).join('')||'<span class="muted">No topics detected.</span>';$('#transcriptView').textContent=transcript;renderSpeakers(r);$('#exportActions').innerHTML=[['PDF','pdf'],['Word','docx'],['Markdown','md'],['Save','save']].map(x=>`<button data-export="${x[1]}">${x[0]}</button>`).join('');$$('[data-export]').forEach(b=>b.onclick=()=>b.dataset.export==='save'?saveMeeting():downloadExport(b.dataset.export));}
function fillList(sel,items,empty){$(sel).innerHTML=(items||[]).map(x=>`<li>${esc(x)}</li>`).join('')||`<li>${empty}</li>`}function renderSpeakers(r){const people=Object.entries(r.speaker_notes||{});if(!people.length){$('#speakerArea').hidden=true;return}$('#speakerArea').hidden=false;const tt=r.talk_time||{},ss=r.per_speaker_sentiment||{};$('#speakers').innerHTML=people.map(([name,lines])=>{const pct=tt[name]?.pct||0,sent=ss[name]?.label||'Neutral';return `<article class="speaker-card"><header><b>${esc(name)}</b><small>${pct}% · ${esc(sent)}</small></header><div class="speaker-bar"><span style="width:${Math.min(pct,100)}%"></span></div><p>${esc((lines||[]).slice(0,2).join(' '))}</p></article>`}).join('')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function downloadExport(format){try{const resp=await fetch('/api/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({result:current.result,format})});if(!resp.ok)throw Error('Export failed');const b=await resp.blob(),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${safe(current.result.title)}.${format==='docx'?'docx':format}`;a.click();URL.revokeObjectURL(a.href);toast(`${format.toUpperCase()} exported`)}catch(err){showError(err.message)}}
function safe(s){return String(s||'meeting').replace(/[^a-z0-9_-]+/gi,'_').slice(0,100)||'meeting'}
async function saveMeeting(){if(!current.result)return;try{await api('/api/history',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:current.result.title,transcript:current.transcript,results:current.result})});toast('Saved to local history');loadHistory()}catch(err){showError(err.message)}}
async function loadHistory(){try{const d=await api('/api/history'),list=$('#historyList');if(!d.meetings.length){list.innerHTML='<div class="muted">No saved meetings yet.</div>';return}list.innerHTML=d.meetings.map((m,i)=>`<div class="history-item"><div><b>${esc(m.title)}</b><small>${esc(m.saved_at||'')}</small></div><div><button data-load="${i}">Open</button><button data-delete="${i}">Delete</button></div></div>`).join('');$$('[data-load]').forEach(b=>b.onclick=async()=>{try{const m=d.meetings[+b.dataset.load],rec=await api('/api/history/load',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:m.filename})});current={result:rec.results,transcript:rec.transcript};$('#transcript').value=rec.transcript;render(rec.results,rec.transcript);$('#results').scrollIntoView({behavior:'smooth'})}catch(err){showError(err.message)}});$$('[data-delete]').forEach(b=>b.onclick=async()=>{const m=d.meetings[+b.dataset.delete];if(!confirm(`Delete "${m.title}"?`))return;try{await api('/api/history/'+encodeURIComponent(m.filename),{method:'DELETE'});loadHistory()}catch(err){showError(err.message)}})}catch(err){$('#historyList').innerHTML=`<div class="muted">${esc(err.message)}</div>`}}
$('#refreshHistory').onclick=loadHistory;$('#search').oninput=e=>{const q=e.target.value.toLowerCase(),text=current.transcript||'';$('#transcriptView').innerHTML=esc(text).replace(new RegExp(escapeRegExp(q),'gi'),m=>`<mark>${m}</mark>`)};function escapeRegExp(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
// Copilot
async function askCopilot(message){message=message.trim();if(!message)return;const chat=$('#chat');chat.insertAdjacentHTML('beforeend',`<div class="chat-msg user">${esc(message)}</div>`);$('#copilotInput').value='';const wait=document.createElement('div');wait.className='chat-msg bot thinking';wait.textContent='Thinking…';chat.appendChild(wait);chat.scrollTop=chat.scrollHeight;try{const d=await api('/api/copilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,transcript:current.transcript,result:current.result})});wait.classList.remove('thinking');wait.innerHTML=esc(d.answer).replace(/\n/g,'<br>');$('#copilotMode').textContent=d.mode==='local-llm'?'Local LLM connected':'Meeting engine · optional Ollama upgrade'}catch(err){wait.textContent=err.message}chat.scrollTop=chat.scrollHeight}
$('#copilotForm').onsubmit=e=>{e.preventDefault();askCopilot($('#copilotInput').value)};$$('[data-prompt]').forEach(b=>b.onclick=()=>askCopilot(b.dataset.prompt));
// Calendar / reminders
const now=new Date();$('#remDate').value=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);
$('#addReminder').onclick=()=>{const title=$('#remTitle').value.trim()||'NoTeX meeting';const date=$('#remDate').value,time=$('#remTime').value,dur=+$('#remDuration').value,alertMin=+$('#remAlert').value;if(!date||!time)return showError('Choose a date and time.');const start=new Date(`${date}T${time}`);const end=new Date(start.getTime()+dur*60000);if(Number.isNaN(start.getTime()))return showError('Invalid meeting date/time.');const fmt=d=>{const p=n=>String(n).padStart(2,'0');return `${d.getUTCFullYear()}${p(d.getUTCMonth()+1)}${p(d.getUTCDate())}T${p(d.getUTCHours())}${p(d.getUTCMinutes())}00Z`};const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//NoTeX//Meeting Reminder//EN','BEGIN:VEVENT',`UID:notex-${Date.now()}@local`,`DTSTAMP:${fmt(new Date())}`,`DTSTART:${fmt(start)}`,`DTEND:${fmt(end)}`,`SUMMARY:${icsEscape(title)}`,`DESCRIPTION:Created with NoTeX meeting intelligence.`,`BEGIN:VALARM`,`TRIGGER:-PT${alertMin}M`,'ACTION:DISPLAY',`DESCRIPTION:${icsEscape(title)} starts in ${alertMin} minutes.`,'END:VALARM','END:VEVENT','END:VCALENDAR'].join('\r\n');const blob=new Blob([ics],{type:'text/calendar;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${safe(title)}.ics`;a.click();URL.revokeObjectURL(a.href);$('#reminderNote').textContent=`Calendar reminder created for ${start.toLocaleString()}. The .ics file can be opened in Google Calendar, Outlook or Apple Calendar.`;toast('Calendar reminder created')};function icsEscape(s){return s.replace(/\\/g,'\\\\').replace(/;/g,'\\;').replace(/,/g,'\\,').replace(/\n/g,'\\n')}
loadHistory();
